src/intranet/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from core import views
from django.conf import settings


urlpatterns = [
	url(r'^$', views.home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^login/$', views.login, name='login'),
	url(r'^register/$', views.register, name='register'),
    url(r'^edit_profile/', views.edit_profile),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^hints/$', views.hints, name='hints'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^users/$', views.users, name='users'),
    url(r'^software/$', views.software, name='software'),
    url(r'^lan-archive/(?P<slug>[-\w\d]+)/$', views.lan_archive, name='lan_archive'),
    url(r'^off-topic/menu/$', views.menu, name='menu'),
    url(r'^off-topic/menu/(?P<slug>[-\w\d]+)/$', views.menu_order, name='menu_order'),
    url(r'^off-topic/menu/(?P<slug>[-\w\d]+)/(?P<command>[-_a-z]+)/$', views.menu_order, name='menu_order'),
    url(r'^off-topic/images/$', views.images, name='images'),
    url(r'^off-topic/images/(?P<command>[-_a-z]+)/$', views.images, name='images'),
    url(r'^off-topic/videos/$', views.videos, name='videos'),
    url(r'^off-topic/videos/(?P<command>[-_a-z]+)/$', views.videos, name='videos'),
    url(r'^save_tournament_bracket$', views.save_tournament_bracket),
    url(r'^games/(?P<slug>[-\w\d]+)/$', views.game, name='game'),
    url(r'^games/(?P<slug>[-\w\d]+)/(?P<match_id>[\d]+)/$', views.match, name='match'),
    url(r'^games/(?P<slug>[-\w\d]+)/(?P<match_id>[\d]+)/(?P<command>[-_a-z]+)/$', views.match),
]



if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)

src/core/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.core.validators import  MinValueValidator, MaxValueValidator
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from filer.fields.file import FilerFileField
from filer.fields.image import FilerImageField

from random import shuffle
from datetime import datetime

from core.validators import integer_only


class IntranetMeta(models.Model):
    name = models.CharField(verbose_name="LAN Name", max_length=50, default="Intranet", null=False, blank=False)
    lan_id = models.PositiveIntegerField(verbose_name="LAN ID", unique=True)
    title = models.CharField(verbose_name="Begrüßungstext", max_length=128, default="Herzlich Willkommen im Intranet", null=True, blank=True)
    description = models.TextField(verbose_name="Beschreibung", max_length=1024, null=True, blank=True)
    date = models.DateField(verbose_name="Beginn der LAN")
    image_upload_allowed = models.BooleanField(verbose_name="Alle User dürfen Bilder hochladen?", default=True)
    video_upload_allowed = models.BooleanField(verbose_name="Alle User dürfen Videos hochladen?", default=True)
    active = models.BooleanField(verbose_name="Aktiv?", default=False)

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        verbose_name = "Intranet Metadaten"
        verbose_name_plural = "Intranet Metadaten"
        app_label = "core"
        ordering = ["-lan_id"]


class UserExtension(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField(verbose_name="Geburtstag", null=True, blank=True)
    avatar = models.ImageField(verbose_name="Avatar", upload_to="user_avatar", blank=True, null=True)
    seat = models.CharField(verbose_name="Sitzplatz", max_length=63, null=True, blank=True)
    ip = models.GenericIPAddressField(verbose_name="IP-Adresse", null=True, blank=True)
    participated_lans = models.ManyToManyField(IntranetMeta, verbose_name="Teilgenommene LANs", blank=True, related_name="user_lan")

    @property
    def shortenName(self):
        if len(self.user.username) > 12:
            return "{0}...".format(self.user.username[:13])
        return self.user.username

    def has_user(self):
        return self.user_id is not None

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.avatar.storage, self.avatar.path
        # Delete the model before the file
        super(UserExtension, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)

    class Meta:
        verbose_name = "Zusätzliche Angaben"
        verbose_name_plural = "Zusätzliche Angaben"
        app_label = "core"


class Software(models.Model):
    name = models.CharField(verbose_name="Name", max_length=255, null=False, blank=False)
    file = models.FileField(verbose_name="Dateiupload", upload_to='software')
    description = models.TextField(verbose_name="Beschreibung", max_length=255, null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        verbose_name = "Software"
        verbose_name_plural = "Software"
        app_label = "core"


class Rules(models.Model):
    name = models.CharField(verbose_name="Regelgruppe", max_length=30, null=False, unique=True, blank=False, default="Allgemeine Regeln")
    slug = models.SlugField(verbose_name="Slug", blank=True, unique=True, editable=False)

    def __unicode__(self):
        return u"%s" % (self.name)

    def save(self):
        self.slug = slugify(self.name)
        super(Rules,self).save()

    class Meta:
        verbose_name = "Regelgruppe"
        verbose_name_plural = "Regelgruppen"
        app_label = "core"


class RulesInline(models.Model):
    rules = models.ForeignKey(Rules, verbose_name="Regelgruppe", blank=True, null=True, related_name="inline_rules")
    information = models.TextField(verbose_name="Regel", max_length=512, null=True, blank=True)

    def __unicode__(self):
        return u"%s" % (self.information)

    class Meta:
        verbose_name = "Regel"
        verbose_name_plural = "Regeln"
        app_label = "core"


class Game(models.Model):
    name = models.CharField(verbose_name="Name", max_length=30, unique=True, blank=False, null=False)
    description = models.TextField(verbose_name="Beschreibung / Installationsanleitung", max_length=1024, blank=True, null=True)
    slug = models.SlugField(verbose_name="Slug", blank=True, unique=True, editable=False)
    icon = FilerImageField(verbose_name="Icon", related_name="game_icon", blank=True, null=True)

    def __unicode__(self):
        return u"%s" % (self.name)

    def save(self):
        self.slug = slugify(self.name)
        super(Game,self).save()

    class Meta:
        verbose_name = "Spiel"
        verbose_name_plural = "Spiele"
        ordering = ['name']
        app_label = "core"


class Match(models.Model):
    TEAM_CHOOSE_TYPE = (
        ('None', 'Bitte wählen'),
        ('rand', 'Zufalls Wahl'),
        ('self', 'Eigene Wahl'),
        ('admin', 'Admin Wahl'),
    )
    TOUR_CHOOSE_TYPE = (
        ('None', 'Bitte wählen'),
        ('vs', 'Jeder gegen Jeden'),
        ('tree', 'Turnierbaum'),
        ('tree_loser', 'Turnierbaum mit Loserbracket'),
    )

    lan = models.ForeignKey(IntranetMeta, verbose_name="LAN", related_name="match_lan")
    game = models.ForeignKey(Game, verbose_name="Spiel", blank=False, null=False, related_name="match_game")
    game_mode = models.CharField(verbose_name="Modus", max_length=50, blank=True, null=True)
    player_per_team = models.IntegerField(verbose_name="Spieler pro Team", blank=False, null=False, validators=[MinValueValidator(1)])
    description = models.TextField(verbose_name="Beschreibung", max_length=255, blank=True, null=True)
    user = models.ManyToManyField(User, verbose_name="Spieler", blank=True, related_name="match_user")
    datetime = models.DateTimeField(verbose_name="Startzeit", blank=True, null=True, default=datetime.now)
    team_choose_type = models.CharField(verbose_name="Team Wahl", editable=False, max_length=5, choices=TEAM_CHOOSE_TYPE, default="None", blank=True)
    tour_choose_type = models.CharField(verbose_name="Turnier Wahl", editable=False, max_length=10, choices=TOUR_CHOOSE_TYPE, default="None", blank=True)
    rules = models.TextField(verbose_name="Spielregeln", max_length=1024, null=True, blank=True)

    def __unicode__(self):
        if self.game_mode:
            return u"%s (%svs%s) - %s" % (self.game, self.player_per_team, self.player_per_team, self.game_mode)
        return u"%s (%svs%s)" % (self.game, self.player_per_team, self.player_per_team)

    @property
    def tournamentBracketRounds(self):
        tour_bracket_list = []
        counter = len(self.team_match.all())
        n = counter/2
        round_number = 1

        while counter != 0: 
            if counter <= n:
                n = n/2
                round_number += 1
            tour_bracket_list.append(round_number)
            counter -= 1
        tour_bracket_list[-1] -= 1

        return tour_bracket_list
    
    @property
    def tournamentBracketRoundsWLoser(self):
        tour_bracket_list = []

        # WINNER Bracket
        tour_bracket_list = self.tournamentBracketRounds
        tour_bracket_list.pop()

        # LOSER Bracket
        counter = len(self.team_match.all())
        n = counter*3/4
        round_number = 1
        double_count = True

        while counter > 2: 
            if counter <= n:
                round_number += 1
                if not double_count:
                    n = n*3/4
                    double_count = True
                else:
                    n = n*2/3
                    double_count = False
            tour_bracket_list.append(round_number)
            counter -= 1

        # FINALS
        tour_bracket_list.extend([1,1,2])

        return tour_bracket_list

    def matchDesciption(self):
        if self.game_mode:
            return u"%svs%s (%s)" % (self.player_per_team, self.player_per_team, self.game_mode)
        return u"%svs%s" % (self.player_per_team, self.player_per_team)

    def getNewTeamNumber(self):
        teams = self.team_match.all().order_by('-description')
        try:
            return int(teams[0].description) + 1
        except IndexError:
            return 1

    def playerWithoutTeam(self):
        player_list = []
        exclude_list = []
        teams = self.team_match.all()
        for team in teams:
            exclude_list.append(team.user.all())
        exclude_list = [item for sublist in exclude_list for item in sublist]
        for user in self.user.all():
            if not user in exclude_list:
                player_list.append(user)
        return player_list

    def playerWithoutTeamIds(self):
        player_list = []
        for user in self.playerWithoutTeam():
            player_list.append(user.id)
        return player_list

    def save_new_user(self, user_id):
        self.user.add(User.objects.get(id=user_id))
        self.save()

    def rem_new_user(self, user_id):
        self.user.remove(User.objects.get(id=user_id))
        self.save() 

    def button_label(self, user_id):
        user = User.objects.get(id=user_id)
        if user in self.user.all():
            return "Abmelden"
        return "Anmelden"
        
    def randomTeams(self):
        """ delete all teams """
        teams = self.team_match.all()
        teams.delete()

        """ create random teams """
        users = list(self.user.all())
        shuffle(users)
        counter = 0
        if self.player_per_team == 1:
            for user in users:

src/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import filesizeformat

from datetime import datetime

from core.models import Round, UserExtension, Software, MenuOrder


class UserForm(forms.ModelForm):
    password = forms.CharField(label="Passwort", widget=forms.PasswordInput())
    password_repeat = forms.CharField(label="Passwort wiederholen", widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password', 'password_repeat')

    def clean_username(self):
        username = self.cleaned_data['username']
        users = User.objects.all()
        for user in users:
            if username.lower() == user.username.lower():
                raise forms.ValidationError('Username schon vorhanden.')

        return username


class UserProfileForm(forms.ModelForm):
    birthdate = forms.DateField(label="Geburtstag", input_formats=settings.DATE_INPUT_FORMATS, required=False)

    class Meta:
        model = UserExtension
        fields = ('user', 'birthdate', 'avatar')

    def clean_user(self):
        return self.cleaned_data['user']

    def clean_birthdate(self):
        return self.cleaned_data['birthdate']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        try:
            #w, h = get_image_dimensions(avatar)

            #validate dimensions
            #max_width = max_height = 100
            #if w > max_width or h > max_height:
            #    raise forms.ValidationError(
            #        u'Please use an image that is '
            #         '%s x %s pixels or smaller.' % (max_width, max_height))

            #validate content type
            main, sub = avatar.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError('Erlaubte Bildformate sind: JPEG, GIF und PNG.')

            #validate file size
            if len(avatar) > (3 * 1024 * 1024):
                raise forms.ValidationError(
                    'Datei überschreitet die maximale Größe von 3 MB')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass

        return avatar


class SoftwareForm(forms.ModelForm):
    class Meta:
        model = Software
        fields = ('name', 'file', 'description',)


class MenuOrderForm(forms.ModelForm):
    description = forms.CharField(error_messages={'required': 'Bitte den Namen des Lieferdienstes eintragen'})
    class Meta:
        model = MenuOrder
        fields = ('description', 'creator', 'venue', 'timestamp')


class ImageForm(forms.Form):
    image = forms.ImageField()

    def clean_image(self):
        image = self.cleaned_data['image']
        content_type = image.content_type.split('/')[0]
        if content_type == "image":
            if image._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(image._size)))
        else:
            raise forms.ValidationError(_('File type is not supported'))
        return image


class VideoForm(forms.Form):
    video = forms.FileField()

    def clean_video(self):
        video = self.cleaned_data['video']
        content_type = video.content_type.split('/')[0]
        if content_type == "video":
            if video._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(video._size)))
        else:
            raise forms.ValidationError(_('File type is not supported'))
        return video


class RoundForm(forms.ModelForm):
    class Meta:
        model = Round
        fields = ('pkt1', 'pkt2')

src/core/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load helper %}
{% load thumbnail %}

<html lang="de">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{{ lan_name.name }}: Intranet{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bracket.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/screen.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/drop_down_menu.css' %}">
        <link rel='stylesheet' type="text/css" href="{% static 'unitegallery/css/unite-gallery.css' %}">
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <!-- Intranet Title -->
        <div class="header_banner">
            <h1>{{ lan_name.name }}</h1>
        </div>

        <!-- Drop Down Menu -->
        <ul class="menu">
            <li><a href="/">Startseite</a></li>
            <li><a href="#">Internes</a>
                <ul>
                    <li><a href="{% url 'hints' %}" class="documents">Hinweise</a></li>
                    <li><a href="{% url 'rules' %}" class="documents">Regeln</a></li>
                    <li><a href="{% url 'users' %}" class="documents">Teilnehmer</a></li>
                </ul>
            </li>
            <li class="menu-tournaments"><a href="#">Turniere</a>
                <ul>
                    {% for game in games %}
                        <li><a href="/games/{{ game.slug }}" class="documents" style="background: url({{ game.icon|thumbnail_url:'game_icon' }}) no-repeat 6px center;">{{ game.name|shortenString }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li><a href="#">LAN-Archiv</a>
                <ul>
                    {% for lanparty in lanparties %}
                        <li><a href="/lan-archive/{{ lanparty.lan_id }}" class="documents">{{ lanparty.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li><a href="#">Offtopic</a>
                <ul>
                    <li><a href="{% url 'menu' %}" class="documents">Lieferdienst</a></li>
                    <li><a href="{% url 'images' %}" class="documents">Bilder</a></li>
                    <li><a href="{% url 'videos' %}" class="documents">Videos</a></li>
                    <li><a href="{% url 'software' %}" class="documents">Software</a></li>
                </ul>
            </li>
        </ul>

        <div class="site-header row">
            <div class="col-sm-2"></div>
            <div class="site-header-headline col-sm-8">
                {% block headline %}
                {% endblock %}
            </div>
            <div class="col-sm-2">
                <!-- User Info Field -->
                {% if user.is_authenticated %}
                    <div class="username_header">
                        <h5>Angemeldet als:</h5>
                        <h4>{{ user.userextension.shortenName }}</h4>
                        <a href="/edit_profile">Editieren</a>
                        <a href="/logout">Logout</a>
                    </div>
                {% else %}
                    <div class="username_header login">
                        <a href="/register">Registrieren</a>
                        <a href="/login">Login</a>
                    </div>
                {% endif %}
            </div>
        </div>
        {% block body %}
        {% endblock %}
        <footer>
            <div class="left">&copy; {% now "Y" %} Carlo Völker</div>
        </footer>
        <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'flipclock/compiled/flipclock.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type='text/javascript' src="{% static 'unitegallery/js/jquery-11.0.min.js' %}"></script>
        <script type='text/javascript' src="{% static 'unitegallery/js/unitegallery.min.js' %}"></script>
	    <script type='text/javascript' src="{% static 'unitegallery/themes/tiles/ug-theme-tiles.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>

src/core/templates/edit_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block headline %}
    <h1>Profil editieren</h1>
{% endblock %}

{% block body %}
{{block.super}}
<div class="content">
	<div class="login-box">
		{% if success %}
            <div class="success row">
	    		<h4>Daten erfolgreich aktualisiert.</h4>
		    </div>
        {% endif %}

		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-group row">
				<label class="col-sm-3 col-form-label" for="id_username">Username</label>
				<div class="col-sm-9">
                    <input class="form-control" id="id_username" name="username" type="text" value="{{ user.username }}" disabled>
			    </div>
            </div>
			<div class="form-group row">
                {{ userprofileform.first_name.errors }}
				<label class="col-sm-3 col-form-label" for="id_first_name">Vorname</label>
				<div class="col-sm-9">
                    <input class="form-control" id="id_first_name" name="first_name" type="text" maxlength="30" value="{{ user.first_name }}" pattern="[A-Za-z]" title="Nur Buchstaben erlaubt">
			    </div>
            </div>
			<div class="form-group row">
                {{ userprofileform.last_name.errors }}
				<label class="col-sm-3 col-form-label" for="id_last_name">Nachname</label>
                <div class="col-sm-9">
                    <input class="form-control" id="id_last_name" name="last_name" type="text" maxlength="30" value="{{ user.last_name }}" pattern="[A-Za-z]" title="Nur Buchstaben erlaubt">
			    </div>
            </div>
			<div class="form-group row">
                {{ userprofileform.birthdate.errors }}
				<label class="col-sm-3 col-form-label" for="id_birthdate">Geburtstag</label>
                <div class="col-sm-9">
                    <input class="form-control" id="id_birthdate" name="birthdate" type="text" value="{{ user.userextension.birthdate|date:'d.m.Y' }}">
			    </div>
            </div>
			<div class="form-group row">
                {{ userprofileform.avatar.errors }}
				<label class="col-sm-3 col-form-label">Avatar</label>
                <div class="col-sm-9">
                    {{ userprofileform.avatar }}
					<img src="{{ user.userextension.avatar|thumbnail_url:'avatar' }}" alt="">
				</div>
			</div>
            <div class="form-group row">
                <div class="offset-sm-4">
    			    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>
            <input type="hidden" name="user" id="id_user" value="{{ user.id }}">
		</form>
	</div>
</div>
{% endblock %}

src/core/templates/game.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load helper %}

{% block headline %}
    <h1>{{ game.name }}</h1>
{% endblock %}

{% block body %}
{{block.super}}
<div class="content">
    {% if game.icon %}
        <div class="game_avatar">
            <img src="{{ game.icon|thumbnail_url:'game_site' }}" />
        </div>
    {% endif %}

	{% if game.description %}
		<div class="game_info_overview">
			{% for line in game.description.splitlines %}
				<span>{{ line }}</span><br/>
			{% endfor %}
		</div>
	{% endif %}

	<div class="match_list">
		{% for match in matches.all %}
			<a class="game-match-link" href="{% url 'match' match.game.slug match.id %}">{{ match.matchDesciption }}</a>
			<br/>
		{% endfor %}
	</div>
</div>
{% endblock %}

src/core/templates/images.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load helper %}

{% block headline %}
    <h1>Bilder</h1>
{% endblock %}

{% block body %}
{{block.super}}
<div class="content-image-gallery">
    <div class="image-gallery-intern">
        {% for category in content.categories %}
            <h2 class="image-gallery-intern-headline">{{ category }}</h2>
            <div id="image-gallery-intern-{{ forloop.counter }}" style="display:none;">
                {% for image in category.image_imagecategory.all %}
                    <img alt="{{ image.image }}"
                         src="{{ image.image.url }}"
                         data-image="{{ image.image.url }}"
                         data-image-mobile="{{ image.image.url }}"
                         data-thumb-mobile="{{ image.image.url }}"
                         data-description="{{ image.image }}"
                         style="display:none">
                {% endfor %}
            </div>
        {% endfor %}
    </div>

    <div class="image-gallery-extern">
        {% for folder, files in content.imageFiler.items %}
            <h2 class="image-gallery-extern-headline">{% if folder == "." %}Rest{% else %}{{ folder|splitOnSlash }}{% endif %}</h2>
            <div id="image-gallery-extern-{{ forloop.counter }}" style="display:none;">
                {% for image in files %}
                    <img alt="{{ image }}"
                         src="{{MEDIA_URL}}image_gallery/{{ image }}"
                         data-image="{{MEDIA_URL}}image_gallery/{{ image }}"
                         data-image-mobile="{{MEDIA_URL}}image_gallery/{{ image }}"
                         data-thumb-mobile="{{MEDIA_URL}}image_gallery/{{ image }}"
                         data-description="{{ image }}"
                         style="display:none">
                {% endfor %}
            </div>
        {% endfor %}
    </div>

    {% if content.upload_allowed and not user|has_group:"Upload-Ban" or user|has_group:"Image-Admin" or user|has_group:"Admin" %}
    <div class="admin_interface well row">
        <h3 class="col-sm-12">Bild Upload</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input id="id_image" name="image" type="file">
            <button class="btn btn-primary btn-sm" type="submit">Upload</button>
        </form>
    </div>
    {% endif %}

    {% if user|has_group:"Admin" %}
    <div class="admin_interface well row">
        <h3 class="col-sm-12">Admin Panel</h3>
        <form method="post" action="upload-lock/">
            {% csrf_token %}
            <button class="btn btn-primary btn-sm" type="submit">{% if content.upload_allowed %}Uploads verbieten{% else %}Upload erlauben{% endif %}</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    jQuery(document).ready(function(){
        {% for category in content.categories %}
            jQuery("#image-gallery-intern-{{ forloop.counter }}").unitegallery({
                tiles_type:"nested",
                tiles_nested_optimal_tile_width: 300
            });
        {% endfor %}
        {% for folder in content.imageFiler %}
            jQuery("#image-gallery-extern-{{ forloop.counter }}").unitegallery({
                tiles_type:"nested",
                tiles_nested_optimal_tile_width: 300
            });
        {% endfor %}
    });
</script>
{% endblock %}

src/core/templates/software.html
{% extends "base.html" %}
{% load helper %}

{% block headline %}
    <h1>Software</h1>
{% endblock %}

{% block body %}
{{block.super}}
<div class="content">
    <div class="software-download row">
    {% for file in software %}
        <div class="software-download-file col-sm-6">
            <h3>{{ file.name }}</h3>
            <p>{{ file.description }}</p>
            <a href="{{ file.file.url }}">Download</a>
        </div>
    {% endfor %}
    </div>

    {% if user|has_group:"Admin" or user|has_group:"Software-Admin" %}
    <div class="admin_interface well row">
        <h3 class="col-sm-12">Dateiupload</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name</label>
                {{ form.name.errors }}
                <input class="form-control" id="id_name" maxlength="255" name="name" type="text" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
            </div>
            <div class="form-group">
                <label for="id_description">Beschreibung</label>
                {{ form.description.errors }}
                <textarea class="form-control" id="id_description" maxlength="255" name="description" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="id_file">Datei</label>
                {{ form.file.errors }}
                <input id="id_file" name="file" type="file">
            </div>
            <button class="btn btn-primary btn-sm" type="submit">Upload</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}